---
title: "COVID-19 in Russia, weekly report"
output: html_document
---

**Коронавирус в России.** Графический update на **`r .ISOweeks.REPORT_TIMESTAMP`** (за неделю, заканчивающуюся **`r .ISOweeks.WEEK_END`**). Прирост зарегистрированных случаев за неделю -- **`r .ISOweeks.lastweek_CONFIRMED`**, всего официально зарегистрированных случаев по России c момента начала эпидемии -- **`r .ISOweeks.cumulated_CONFIRMED.txt`**. Прирост связанных с COVID смертей за неделю: **`r .ISOweeks.lastweek_DEATHS`**, всего с начала эпидемии в оперативных сводках зарегистрировано смертей: **`r .ISOweeks.cumulated_DEATHS.txt`** (следует помнить, что число это заведомо занижено, суммарная избыточная смертность за время пандемии составила в Российской Федерации **более 1.3 млн.** чел.). Суммарный прирост новых случаев за последние две недели на 100 тыс. населения -- **`r .ISOweeks.14_100`**.

**Лидеры по абсолютному приросту и госпитализациям за неделю (выявленные : госпитализированные : умершие)**: 

```{r results='asis', echo = FALSE}
knitr::kable(.ISOweeks.top$txt, caption="")
```

<!-- **Техническое.** В виду многочисленности графиков по регионам, отсылаю за ними к папкам в репозитории. 

* **Графики по регионам:** < https://github.com/alexei-kouprianov/COVID.2019.ru/tree/master/plots/regions >

* **Скрипт и данные.** < https://github.com/alexei-kouprianov/COVID.2019.ru > -->

* **Исходные данные:** < https://стопкоронавирус.рф/information/ >
* **Репозиторий со скриптами и данными:** < https://github.com/alexei-kouprianov/COVID-2019.ru.ISOWeeks >
